### PR TITLE
First tests event characteristics

### PR DESCRIPTION
**Pull request by Hendrik1704**
This adds the first tests for the EventCharacteristics class (initialization and eccentricity). The smearing of the densities is not tested yet.
I also added an optional different weight for the radius in the eccentricity calculation and fixed the sign of the eccentricities. There was a minus missing.
The documentation string contains the eccentricity formula now.

I also fixed a small error in the documentation of the Histogram class, which I noticed while compiling the documentation.

### CODE REVIEW

**Comment by Hendrik1704** [comment]
I added some tests for the errors of the smearing functions. We still have to check the physics. In the Milne coordinate smearing, I'm still not sure, if the dimensions are correct. Maybe there is a factor of $\tau$ missing somewhere...

**Comment by NGoetz** [comment]
I agree that physics tests are still needed. At which point are you unsure about the Milne coordinate smearing. Is it the conversion factor?

**Comment by NGoetz** [comment]
I add quite a bunch of additional misusage tests. For the physics tests, though, I am sceptical - isn't that just test duplication of the lattice class?

**Comment by NGoetz** [comment]
@Hendrik1704  how do you feel about this test? Should there be more?

**Comment by NGoetz** [comment]
I added @nilssass as a reviewer as both of us have now worked on this.

**Pull request merged**
