### PR TITLE
Sass/histogram bug fix

### PR DESCRIPTION
**Pull request by nilssass**
This PR fixes Issue #315

### CODE REVIEW

**Comment by NGoetz** [comment]
What happened in the commit history

**Review by NGoetz — APPROVED** [review]
I approve, but please check what happened in the history

**Comment by nilssass** [comment]
I have no clue, I had to merge origin into my local sparkx-devel as there was a deviation. Maybe it originates from the merge

**Comment by NGoetz** [comment]
You have a last version tag merge there. What happens if you cherry pick your fix on a fresh branch from devel

**Comment by nilssass** [comment]
With the power of an AI driven approach, I could solve the issue and now the history is clean

**Pull request merged**
