### PR TITLE
Add new filters + fix statical typing for external packages

### PR DESCRIPTION
**Pull request by Hendrik1704**
This PR adds multiple new filter functions and also functions in the Particle class.
I also tried to fix the static typing warnings from the external packages by explicitly switching off the checks for these imports.

The tests and the static typing should then be fine with these changes.

One other thing I noticed was the documentation of the Jetscape and the Oscar classes. This is something we should take a look at. For example, in Jetscape there are some functions not documented and there are some which do not apply in this class. Probably similar for Oscar.

### CODE REVIEW

**Comment by Hendrik1704** [comment]
It seems that the mypy run on my laptop is successful, while the GH action produces an error. I'll try to investigate this.

**Comment by Hendrik1704** [comment]
I found that we run `mypy src/sparkx --ignore-missing-imports --show-error-codes --disallow-untyped-defs --disallow-untyped-calls`. The last two arguments `--disallow-untyped-defs --disallow-untyped-calls` are causing the action to fail.
@NGoetz Should I just remove them from the action?

**Comment by NGoetz** [comment]
Should we not rather fix untyped calls and defs instead?

**Comment by NGoetz** [comment]
Can you point out the mistakes in the documentation, or open an issue?

**Review by NGoetz — APPROVED** [review]
Looks good!

**Pull request merged**
