### PR TITLE
Add JS partons

### LINKED ISSUE #180: Allow for JETSCAPE parton files in read in function
We could allow the JETSCAPE Parton file to read in with the Jetscape class. This requires only minor changes (instead of `N_hadrons` this needs `N_partons` in some places). 
In the constructor of the class, we could have a switch parameter, which is set to hadrons by default, and then for the use with the parton file, one could switch to this format by hand.

### PR DESCRIPTION
**Pull request by Hendrik1704**
This implements the possibility to read in JETSCAPE parton output files with the Jetscape class in SPARKX. To switch to the parton mode there is a keyword argument called `particletype` in the constructor, which can be set to `parton`. 
By default, it is set to `hadron`, such that the current behavior in any script used so far does not change.
This closes #180.
The corresponding documentation is added and the CHANGELOG is updated.

I tested this with one of my current parton output files. However, I will add some more rigorous testing methods for the Jetscape class in the tests for SPARKX. This is part of #147.

### CODE REVIEW

**Review by NGoetz — APPROVED** [review]
It looks good, I just wonder - does anything about particle class need to be changed for this? Like with respect to fractional charges etc. . Is the data represented correctly?

**Comment by Hendrik1704** [comment]
That is a good question, I have to check this. I just tested the reading of the input file. I guess I can just test the write to file function for some of the quantities. The other ones have to be tested by hand.
I think the PDGID package knows about quarks and their quantities. Maybe it is a problem that the charge is not int.

**Comment by Hendrik1704** [comment]
I did some further tests with the particle quantities:
```
print(had_epem_decays[0][0].ID) -> correct
print(had_epem_decays[0][0].pdg) -> correct
print(had_epem_decays[0][0].status) -> correct
print(had_epem_decays[0][0].E) -> correct
print(had_epem_decays[0][0].px) -> correct
print(had_epem_decays[0][0].py) -> correct
print(had_epem_decays[0][0].pz) -> correct
print(had_epem_decays[0][0].mass) -> correct
print(had_epem_decays[0][0].charge) -> wrong, always 0 (cast to int)
print(had_epem_decays[0][0].is_strange()) -> wrong, always gives False
print(had_epem_decays[0][0].is_heavy_flavor()) -> wrong, always gives False
print(had_epem_decays[0][0].spin()) -> correct
print(had_epem_decays[0][0].spin_degeneracy()) -> correct
print(had_epem_decays[0][0].is_hadron()) -> correct, always False
print(had_epem_decays[0][0].is_meson()) -> correct, always False
print(had_epem_decays[0][0].is_baryon()) -> correct, always False
print(had_epem_decays[0][0].compute_charge_from_pdg()) -> correct
```
I guess the charge function can be easily fixed. For the other functions it's probably more complicated. There we use the PDGID package.

**Comment by Hendrik1704** [comment]
This adds now a multiplication of parton charges by a factor 3 to make them integers. This is also reflected in the documentation. There are also tests for the Particle class added for this case and I test with Jetscape to read a parton file and filter for charged partons.

**Review by NGoetz — APPROVED** [review]
Thank you, this looks good!

**Pull request merged**
